_BASE_: "../Base_det.yaml"

MODEL:
#  WEIGHTS: "output/R50/150k_tt_mlt_13_15_textocr/pretrain/model_final.pth"
  WEIGHTS: "/media/WD_2T/chill_research/deepsolo/pretrain_weights/res50_pretrain_synth-tt-mlt-13-15-textocr.pth"
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.3

DATASETS:
  TRAIN: ("ic15_train",)
  TEST: ("ic15_test",)

INPUT:
#  MIN_SIZE_TRAIN: (800,900,1000,1100,1200,1300,1400)
#  MAX_SIZE_TRAIN: 3000
#  MIN_SIZE_TEST: 1440
#  MAX_SIZE_TEST: 4000
  MIN_SIZE_TRAIN: (480, 576, 672, 768, 896)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1200
  CROP:
    ENABLED: False
  ROTATE: False

SOLVER:
#  IMS_PER_BATCH: 8
  IMS_PER_BATCH: 4
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
#  STEPS: (100000,)  # no step
  STEPS: (4000,)  # no step
#  MAX_ITER: 1000
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000
  # 1 - Generic, 2 - Weak, 3 - Strong (for icdar2015)
  LEXICON_TYPE: 3

OUTPUT_DIR: "output/R50/ic15"